### ISSUE TITLE
URL query parameters are not passed down to PHP

### ISSUE THREAD

**Issue by berrnd** [Tallyrald/grocy-install#4]
Grocy relies here and there (e.g. pretty much all dialogs) heavily on URL query parameters. This line in `nginx_grocy.conf` clearly doesn't pass them down to PHP, leading to a lot of stuff not working properly:

https://github.com/Tallyrald/grocy-install/blob/159e41bad8d1a53b35e99a6d225ccf9c877fc3bf/nginx_grocy.conf#L6

Changing this to that makes it work better:
```
try_files $uri /index.php$is_args$query_string;
```

That's even noted in [Grocy's README](https://github.com/grocy/grocy?tab=readme-ov-file#how-to-install) and I'm a little surprised how this can go unnoticed when using/testing this just once...

Originally noted by @Saturo78 in https://www.reddit.com/r/grocy/comments/1alegbh/comment/l0ks07h/?context=3.

**Comment by Tallyrald** [comment]
Hi @berrnd ! This script is more than 3 years old and at the time I've used Grocy based on this exact setup for several weeks without any issues. Since then you've released a lot of versions so it's not actually that surprising that some functionality may be broken in this configuration. Currently I'm not using Grocy at all as it causes too much overhead on my everyday life, so testing the change you propose is not a priority for me.

In the Reddit post you linked, the conversation suggests that Saturo's issues may have been due to a corrupt database file rather than an NGINX config problem. I haven't had any reports of anything similar since posting the [original guide](https://www.reddit.com/r/grocy/comments/qvckh7/free_googlehosted_httpssecured_grocy_installation/) on Reddit all those years ago.

Then again this configuration is using fastcgi, and if I remember correctly any routing changes should go into the fastcgi_params.conf file and not into the NGINX config. (Haven't used fastcgi in a while so I'm not 100% sure)

Anyhow if you (or someone else) have the time and are able to test whether this change actually fixes any issues, feel free to open a PR.

**Comment by berrnd** [comment]
> This script is more than 3 years old and at the time I've used Grocy based on this exact setup for several weeks without any issues.
> Currently I'm not using Grocy at all as it causes too much overhead on my everyday life

That's fine but I can't believe everything worked 3 years ago, since Grocy relies on URL query parameters since ever. Of course you maybe don't notice that when not using every single in-depth detail.

&nbsp;
> In the Reddit post you linked, the conversation suggests that Saturo's issues may have been due to a corrupt database file rather than an NGINX config problem

You've mixed that up and/or not read it fully. @Saturo78 just abused the month old thread, his reported "problem" there is completely unrelated to the OP's one and at no place a "corrupt database" was mentioned (whatever that should be). It's clearly about the nginx config issue pointed out now multiple times.

&nbsp;
> Then again this configuration is using fastcgi, and if I remember correctly any routing changes should go into the fastcgi_params.conf file and not into the NGINX config.

Bullshit. `try_files $uri /index.php;` clearly strips any URL query parameters, so they don't hit upstream / FastCGI and that's the problem.

&nbsp;
> Anyhow if you (or someone else) have the time and are able to test whether this change actually fixes any issues, feel free to open a PR.

Sorry, I won't invest any time here and can just recommend to clearly communicate (README is a good place) that this project is then more outdated / not working / not maintained. Crystal clear communication is IMHO always better than publishing false expectations, even more important if you are yourself maybe not 100 % familiar with the technical stuff involved.

Just wanted to report that this here as-is can't work, nothing more or less - the support workload for anything Grocy, even if unrelated to Grocy itself, lands just as always on my side and of course I love that.

**Comment by Tallyrald** [comment]
Man, your beatifully aggressive nature is such a delight, I love you.
